api_platform:
    path_segment_name_generator: 'api_platform.path_segment_name_generator.dash'
    collection:
        pagination:
            enabled: true
            items_per_page: 10

    mapping:
        paths:
            - '%kernel.project_dir%/config/packages/apiplatform/tempUser.yml'
            - '%kernel.project_dir%/config/packages/apiplatform/otrasEspecies.yml'
            - '%kernel.project_dir%/config/packages/apiplatform/locNidosCol.yml'
            - '%kernel.project_dir%/config/packages/apiplatform/colonia.yml'
            - '%kernel.project_dir%/config/packages/apiplatform/territorio.yml'
            - '%kernel.project_dir%/src/Entity'
