easy_admin:
    entities:
        # List the entity class name you want to manage
        Colonia:
            class: App\Entity\Colonia
        LocNidosCol:
            class: App\Entity\LocNidosCol
        FavoritosCol:
            class: App\Entity\FavoritosCol
        OtrasEspecies:
            class: App\Entity\OtrasEspecies
        VisitasColonia:
            class: App\Entity\VisitasColonia
        VisitaColoniaImages:
            class: App\Entity\VisitaColoniaImages
        Territorio:
            class: App\Entity\Territorio
        FavoritosTerr:
            class: App\Entity\FavoritosTerr
        LocNidosNoCol:
            class: App\Entity\LocNidosNoCol
        VisitasTerritorio:
            class: App\Entity\VisitasTerritorio
        VisitaTerritorioImages:
            class: App\Entity\VisitaTerritorioImages
        SegUsu:
            class: App\Entity\SegUsu
        CensoMunicipio:
            class: App\Entity\CensoMunicipio
        Emplazamiento:
            class: App\Entity\Emplazamiento
        ObservacionesTerritorio:
            class: App\Entity\ObservacionesTerritorio
        Temporada:
            class: App\Entity\Temporada
        TipoEdificio:
            class: App\Entity\TipoEdificio
        TipoPropiedad:
            class: App\Entity\TipoPropiedad
        TipoTerritorio:
            class: App\Entity\TipoTerritorio
