easy_admin:
    entities:
        # List the entity class name you want to manage
        Colonia:
            class: App\Entity\Colonia
        Territorio:
            class: App\Entity\Territorio
        SegUsu:
            class: App\Entity\SegUsu
