<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine.orm.container_repository_factory' shared service.

include_once $this->targetDirs[3].'/vendor/doctrine/orm/lib/Doctrine/ORM/Repository/RepositoryFactory.php';
include_once $this->targetDirs[3].'/vendor/doctrine/doctrine-bundle/Repository/ContainerRepositoryFactory.php';

return $this->services['doctrine.orm.container_repository_factory'] = new \Doctrine\Bundle\DoctrineBundle\Repository\ContainerRepositoryFactory(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Repository\\CensoMunicipioRepository' => function () {
    return ${($_ = isset($this->services['App\Repository\CensoMunicipioRepository']) ? $this->services['App\Repository\CensoMunicipioRepository'] : $this->load('getCensoMunicipioRepositoryService.php')) && false ?: '_'};
}, 'App\\Repository\\ColoniaRepository' => function () {
    return ${($_ = isset($this->services['App\Repository\ColoniaRepository']) ? $this->services['App\Repository\ColoniaRepository'] : $this->load('getColoniaRepositoryService.php')) && false ?: '_'};
}, 'App\\Repository\\ComunidadesRepository' => function () {
    return ${($_ = isset($this->services['App\Repository\ComunidadesRepository']) ? $this->services['App\Repository\ComunidadesRepository'] : $this->load('getComunidadesRepositoryService.php')) && false ?: '_'};
}, 'App\\Repository\\EmplazamientoRepository' => function () {
    return ${($_ = isset($this->services['App\Repository\EmplazamientoRepository']) ? $this->services['App\Repository\EmplazamientoRepository'] : $this->load('getEmplazamientoRepositoryService.php')) && false ?: '_'};
}, 'App\\Repository\\LocNidosColRepository' => function () {
    return ${($_ = isset($this->services['App\Repository\LocNidosColRepository']) ? $this->services['App\Repository\LocNidosColRepository'] : $this->load('getLocNidosColRepositoryService.php')) && false ?: '_'};
}, 'App\\Repository\\LocNidosNoColRepository' => function () {
    return ${($_ = isset($this->services['App\Repository\LocNidosNoColRepository']) ? $this->services['App\Repository\LocNidosNoColRepository'] : $this->load('getLocNidosNoColRepositoryService.php')) && false ?: '_'};
}, 'App\\Repository\\PoblacionesRepository' => function () {
    return ${($_ = isset($this->services['App\Repository\PoblacionesRepository']) ? $this->services['App\Repository\PoblacionesRepository'] : $this->load('getPoblacionesRepositoryService.php')) && false ?: '_'};
}, 'App\\Repository\\ProvinciasRepository' => function () {
    return ${($_ = isset($this->services['App\Repository\ProvinciasRepository']) ? $this->services['App\Repository\ProvinciasRepository'] : $this->load('getProvinciasRepositoryService.php')) && false ?: '_'};
}, 'App\\Repository\\TempUserRepository' => function () {
    return ${($_ = isset($this->services['App\Repository\TempUserRepository']) ? $this->services['App\Repository\TempUserRepository'] : $this->load('getTempUserRepositoryService.php')) && false ?: '_'};
}, 'App\\Repository\\TerritorioRepository' => function () {
    return ${($_ = isset($this->services['App\Repository\TerritorioRepository']) ? $this->services['App\Repository\TerritorioRepository'] : $this->load('getTerritorioRepositoryService.php')) && false ?: '_'};
}, 'App\\Repository\\TipoEdificioRepository' => function () {
    return ${($_ = isset($this->services['App\Repository\TipoEdificioRepository']) ? $this->services['App\Repository\TipoEdificioRepository'] : $this->load('getTipoEdificioRepositoryService.php')) && false ?: '_'};
}, 'App\\Repository\\TipoPropiedadRepository' => function () {
    return ${($_ = isset($this->services['App\Repository\TipoPropiedadRepository']) ? $this->services['App\Repository\TipoPropiedadRepository'] : $this->load('getTipoPropiedadRepositoryService.php')) && false ?: '_'};
}, 'App\\Repository\\VisitasColoniaRepository' => function () {
    return ${($_ = isset($this->services['App\Repository\VisitasColoniaRepository']) ? $this->services['App\Repository\VisitasColoniaRepository'] : $this->load('getVisitasColoniaRepositoryService.php')) && false ?: '_'};
})));
