<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Territorio extends \App\Entity\Territorio implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Territorio' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Territorio' . "\0" . 'usuario', '' . "\0" . 'App\\Entity\\Territorio' . "\0" . 'especie', '' . "\0" . 'App\\Entity\\Territorio' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\Territorio' . "\0" . 'barrio', '' . "\0" . 'App\\Entity\\Territorio' . "\0" . 'calleNumPiso', '' . "\0" . 'App\\Entity\\Territorio' . "\0" . 'nombreCentro', '' . "\0" . 'App\\Entity\\Territorio' . "\0" . 'tipoPropiedad', '' . "\0" . 'App\\Entity\\Territorio' . "\0" . 'tipoEdificio', '' . "\0" . 'App\\Entity\\Territorio' . "\0" . 'locNidos', '' . "\0" . 'App\\Entity\\Territorio' . "\0" . 'amenazada', '' . "\0" . 'App\\Entity\\Territorio' . "\0" . 'vacio', '' . "\0" . 'App\\Entity\\Territorio' . "\0" . 'ccaa', '' . "\0" . 'App\\Entity\\Territorio' . "\0" . 'provincia', '' . "\0" . 'App\\Entity\\Territorio' . "\0" . 'municipio', '' . "\0" . 'App\\Entity\\Territorio' . "\0" . 'temporada', '' . "\0" . 'App\\Entity\\Territorio' . "\0" . 'tipo', '' . "\0" . 'App\\Entity\\Territorio' . "\0" . 'visitasTerritorios'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Territorio' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Territorio' . "\0" . 'usuario', '' . "\0" . 'App\\Entity\\Territorio' . "\0" . 'especie', '' . "\0" . 'App\\Entity\\Territorio' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\Territorio' . "\0" . 'barrio', '' . "\0" . 'App\\Entity\\Territorio' . "\0" . 'calleNumPiso', '' . "\0" . 'App\\Entity\\Territorio' . "\0" . 'nombreCentro', '' . "\0" . 'App\\Entity\\Territorio' . "\0" . 'tipoPropiedad', '' . "\0" . 'App\\Entity\\Territorio' . "\0" . 'tipoEdificio', '' . "\0" . 'App\\Entity\\Territorio' . "\0" . 'locNidos', '' . "\0" . 'App\\Entity\\Territorio' . "\0" . 'amenazada', '' . "\0" . 'App\\Entity\\Territorio' . "\0" . 'vacio', '' . "\0" . 'App\\Entity\\Territorio' . "\0" . 'ccaa', '' . "\0" . 'App\\Entity\\Territorio' . "\0" . 'provincia', '' . "\0" . 'App\\Entity\\Territorio' . "\0" . 'municipio', '' . "\0" . 'App\\Entity\\Territorio' . "\0" . 'temporada', '' . "\0" . 'App\\Entity\\Territorio' . "\0" . 'tipo', '' . "\0" . 'App\\Entity\\Territorio' . "\0" . 'visitasTerritorios'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Territorio $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', []);

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario(string $usuario): \App\Entity\Territorio
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', [$usuario]);

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getEspecie(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEspecie', []);

        return parent::getEspecie();
    }

    /**
     * {@inheritDoc}
     */
    public function setEspecie(int $especie): \App\Entity\Territorio
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEspecie', [$especie]);

        return parent::setEspecie($especie);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre(string $nombre): \App\Entity\Territorio
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getBarrio(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBarrio', []);

        return parent::getBarrio();
    }

    /**
     * {@inheritDoc}
     */
    public function setBarrio(string $barrio): \App\Entity\Territorio
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBarrio', [$barrio]);

        return parent::setBarrio($barrio);
    }

    /**
     * {@inheritDoc}
     */
    public function getCalleNumPiso(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCalleNumPiso', []);

        return parent::getCalleNumPiso();
    }

    /**
     * {@inheritDoc}
     */
    public function setCalleNumPiso(string $calleNumPiso): \App\Entity\Territorio
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCalleNumPiso', [$calleNumPiso]);

        return parent::setCalleNumPiso($calleNumPiso);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreCentro(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreCentro', []);

        return parent::getNombreCentro();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreCentro(string $nombreCentro): \App\Entity\Territorio
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreCentro', [$nombreCentro]);

        return parent::setNombreCentro($nombreCentro);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoPropiedad(): \App\Entity\TipoPropiedad
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoPropiedad', []);

        return parent::getTipoPropiedad();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoPropiedad(\App\Entity\TipoPropiedad $tipoPropiedad): \App\Entity\Territorio
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoPropiedad', [$tipoPropiedad]);

        return parent::setTipoPropiedad($tipoPropiedad);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoEdificio(): \App\Entity\TipoEdificio
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoEdificio', []);

        return parent::getTipoEdificio();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoEdificio(\App\Entity\TipoEdificio $tipoEdificio): \App\Entity\Territorio
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoEdificio', [$tipoEdificio]);

        return parent::setTipoEdificio($tipoEdificio);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocNidos(): \App\Entity\LocNidosNoCol
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocNidos', []);

        return parent::getLocNidos();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocNidos(\App\Entity\LocNidosNoCol $locNidos): \App\Entity\Territorio
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocNidos', [$locNidos]);

        return parent::setLocNidos($locNidos);
    }

    /**
     * {@inheritDoc}
     */
    public function getAmenazada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAmenazada', []);

        return parent::getAmenazada();
    }

    /**
     * {@inheritDoc}
     */
    public function setAmenazada(bool $amenazada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAmenazada', [$amenazada]);

        return parent::setAmenazada($amenazada);
    }

    /**
     * {@inheritDoc}
     */
    public function getVacio(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVacio', []);

        return parent::getVacio();
    }

    /**
     * {@inheritDoc}
     */
    public function setVacio(bool $vacio): \App\Entity\Territorio
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVacio', [$vacio]);

        return parent::setVacio($vacio);
    }

    /**
     * {@inheritDoc}
     */
    public function getCcaa(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCcaa', []);

        return parent::getCcaa();
    }

    /**
     * {@inheritDoc}
     */
    public function setCcaa(string $ccaa): \App\Entity\Territorio
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCcaa', [$ccaa]);

        return parent::setCcaa($ccaa);
    }

    /**
     * {@inheritDoc}
     */
    public function getProvincia(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProvincia', []);

        return parent::getProvincia();
    }

    /**
     * {@inheritDoc}
     */
    public function setProvincia(string $provincia): \App\Entity\Territorio
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProvincia', [$provincia]);

        return parent::setProvincia($provincia);
    }

    /**
     * {@inheritDoc}
     */
    public function getMunicipio(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMunicipio', []);

        return parent::getMunicipio();
    }

    /**
     * {@inheritDoc}
     */
    public function setMunicipio(string $municipio): \App\Entity\Territorio
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMunicipio', [$municipio]);

        return parent::setMunicipio($municipio);
    }

    /**
     * {@inheritDoc}
     */
    public function getTemporada(): ?\App\Entity\Temporada
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTemporada', []);

        return parent::getTemporada();
    }

    /**
     * {@inheritDoc}
     */
    public function setTemporada(?\App\Entity\Temporada $temporada): \App\Entity\Territorio
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTemporada', [$temporada]);

        return parent::setTemporada($temporada);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', []);

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo(?\App\Entity\TipoTerritorio $tipo): \App\Entity\Territorio
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', [$tipo]);

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisitasTerritorios(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisitasTerritorios', []);

        return parent::getVisitasTerritorios();
    }

    /**
     * {@inheritDoc}
     */
    public function addVisitasTerritorio(\App\Entity\VisitasTerritorio $visitasTerritorio): \App\Entity\Territorio
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addVisitasTerritorio', [$visitasTerritorio]);

        return parent::addVisitasTerritorio($visitasTerritorio);
    }

    /**
     * {@inheritDoc}
     */
    public function removeVisitasTerritorio(\App\Entity\VisitasTerritorio $visitasTerritorio): \App\Entity\Territorio
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeVisitasTerritorio', [$visitasTerritorio]);

        return parent::removeVisitasTerritorio($visitasTerritorio);
    }

}
