<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class LocNidosCol extends \App\Entity\LocNidosCol implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\LocNidosCol' . "\0" . 'id', '' . "\0" . 'App\\Entity\\LocNidosCol' . "\0" . 'usuario', '' . "\0" . 'App\\Entity\\LocNidosCol' . "\0" . 'fachada', '' . "\0" . 'App\\Entity\\LocNidosCol' . "\0" . 'trasera', '' . "\0" . 'App\\Entity\\LocNidosCol' . "\0" . 'lateralDerecho', '' . "\0" . 'App\\Entity\\LocNidosCol' . "\0" . 'lateralIzquierdo', '' . "\0" . 'App\\Entity\\LocNidosCol' . "\0" . 'patioInferior', '' . "\0" . 'App\\Entity\\LocNidosCol' . "\0" . 'huso', '' . "\0" . 'App\\Entity\\LocNidosCol' . "\0" . 'lat', '' . "\0" . 'App\\Entity\\LocNidosCol' . "\0" . 'lon'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\LocNidosCol' . "\0" . 'id', '' . "\0" . 'App\\Entity\\LocNidosCol' . "\0" . 'usuario', '' . "\0" . 'App\\Entity\\LocNidosCol' . "\0" . 'fachada', '' . "\0" . 'App\\Entity\\LocNidosCol' . "\0" . 'trasera', '' . "\0" . 'App\\Entity\\LocNidosCol' . "\0" . 'lateralDerecho', '' . "\0" . 'App\\Entity\\LocNidosCol' . "\0" . 'lateralIzquierdo', '' . "\0" . 'App\\Entity\\LocNidosCol' . "\0" . 'patioInferior', '' . "\0" . 'App\\Entity\\LocNidosCol' . "\0" . 'huso', '' . "\0" . 'App\\Entity\\LocNidosCol' . "\0" . 'lat', '' . "\0" . 'App\\Entity\\LocNidosCol' . "\0" . 'lon'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (LocNidosCol $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', []);

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario(string $usuario): \App\Entity\LocNidosCol
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', [$usuario]);

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getFachada(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFachada', []);

        return parent::getFachada();
    }

    /**
     * {@inheritDoc}
     */
    public function setFachada(bool $fachada): \App\Entity\LocNidosCol
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFachada', [$fachada]);

        return parent::setFachada($fachada);
    }

    /**
     * {@inheritDoc}
     */
    public function getTrasera(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrasera', []);

        return parent::getTrasera();
    }

    /**
     * {@inheritDoc}
     */
    public function setTrasera(bool $trasera): \App\Entity\LocNidosCol
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTrasera', [$trasera]);

        return parent::setTrasera($trasera);
    }

    /**
     * {@inheritDoc}
     */
    public function getLateralDerecho(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLateralDerecho', []);

        return parent::getLateralDerecho();
    }

    /**
     * {@inheritDoc}
     */
    public function setLateralDerecho(bool $lateralDerecho): \App\Entity\LocNidosCol
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLateralDerecho', [$lateralDerecho]);

        return parent::setLateralDerecho($lateralDerecho);
    }

    /**
     * {@inheritDoc}
     */
    public function getLateralIzquierdo(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLateralIzquierdo', []);

        return parent::getLateralIzquierdo();
    }

    /**
     * {@inheritDoc}
     */
    public function setLateralIzquierdo(bool $lateralIzquierdo): \App\Entity\LocNidosCol
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLateralIzquierdo', [$lateralIzquierdo]);

        return parent::setLateralIzquierdo($lateralIzquierdo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPatioInferior(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPatioInferior', []);

        return parent::getPatioInferior();
    }

    /**
     * {@inheritDoc}
     */
    public function setPatioInferior(bool $patioInferior): \App\Entity\LocNidosCol
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPatioInferior', [$patioInferior]);

        return parent::setPatioInferior($patioInferior);
    }

    /**
     * {@inheritDoc}
     */
    public function getHuso(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHuso', []);

        return parent::getHuso();
    }

    /**
     * {@inheritDoc}
     */
    public function setHuso(string $huso): \App\Entity\LocNidosCol
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHuso', [$huso]);

        return parent::setHuso($huso);
    }

    /**
     * {@inheritDoc}
     */
    public function getLat(): float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLat', []);

        return parent::getLat();
    }

    /**
     * {@inheritDoc}
     */
    public function setLat(float $lat): \App\Entity\LocNidosCol
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLat', [$lat]);

        return parent::setLat($lat);
    }

    /**
     * {@inheritDoc}
     */
    public function getLon(): float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLon', []);

        return parent::getLon();
    }

    /**
     * {@inheritDoc}
     */
    public function setLon(float $lon): \App\Entity\LocNidosCol
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLon', [$lon]);

        return parent::setLon($lon);
    }

}
