<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CensoMunicipio extends \App\Entity\CensoMunicipio implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\CensoMunicipio' . "\0" . 'id', '' . "\0" . 'App\\Entity\\CensoMunicipio' . "\0" . 'usuario', '' . "\0" . 'App\\Entity\\CensoMunicipio' . "\0" . 'municipio', '' . "\0" . 'App\\Entity\\CensoMunicipio' . "\0" . 'especie', '' . "\0" . 'App\\Entity\\CensoMunicipio' . "\0" . 'completo', '' . "\0" . 'App\\Entity\\CensoMunicipio' . "\0" . 'temporada', '' . "\0" . 'App\\Entity\\CensoMunicipio' . "\0" . 'coloniasAsignadas'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\CensoMunicipio' . "\0" . 'id', '' . "\0" . 'App\\Entity\\CensoMunicipio' . "\0" . 'usuario', '' . "\0" . 'App\\Entity\\CensoMunicipio' . "\0" . 'municipio', '' . "\0" . 'App\\Entity\\CensoMunicipio' . "\0" . 'especie', '' . "\0" . 'App\\Entity\\CensoMunicipio' . "\0" . 'completo', '' . "\0" . 'App\\Entity\\CensoMunicipio' . "\0" . 'temporada', '' . "\0" . 'App\\Entity\\CensoMunicipio' . "\0" . 'coloniasAsignadas'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CensoMunicipio $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', []);

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario(string $usuario): \App\Entity\CensoMunicipio
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', [$usuario]);

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getMunicipio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMunicipio', []);

        return parent::getMunicipio();
    }

    /**
     * {@inheritDoc}
     */
    public function setMunicipio(string $municipio): \App\Entity\CensoMunicipio
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMunicipio', [$municipio]);

        return parent::setMunicipio($municipio);
    }

    /**
     * {@inheritDoc}
     */
    public function getEspecie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEspecie', []);

        return parent::getEspecie();
    }

    /**
     * {@inheritDoc}
     */
    public function setEspecie(int $especie): \App\Entity\CensoMunicipio
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEspecie', [$especie]);

        return parent::setEspecie($especie);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompleto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompleto', []);

        return parent::getCompleto();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompleto(bool $completo): \App\Entity\CensoMunicipio
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompleto', [$completo]);

        return parent::setCompleto($completo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTemporada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTemporada', []);

        return parent::getTemporada();
    }

    /**
     * {@inheritDoc}
     */
    public function setTemporada(?\App\Entity\Temporada $temporada): \App\Entity\CensoMunicipio
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTemporada', [$temporada]);

        return parent::setTemporada($temporada);
    }

    /**
     * {@inheritDoc}
     */
    public function getColoniasAsignadas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColoniasAsignadas', []);

        return parent::getColoniasAsignadas();
    }

    /**
     * {@inheritDoc}
     */
    public function addColoniasAsignada(\App\Entity\Colonia $coloniasAsignada): \App\Entity\CensoMunicipio
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addColoniasAsignada', [$coloniasAsignada]);

        return parent::addColoniasAsignada($coloniasAsignada);
    }

    /**
     * {@inheritDoc}
     */
    public function removeColoniasAsignada(\App\Entity\Colonia $coloniasAsignada): \App\Entity\CensoMunicipio
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeColoniasAsignada', [$coloniasAsignada]);

        return parent::removeColoniasAsignada($coloniasAsignada);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
