resources:
    App\Entity\Colonia:
        collectionOperations:
            post:
                method: 'POST'
                route_name: 'api_new_colonia'
                swagger_context:
                    summary: 'Registrar una nueva colonia'
            postCol:
                method: 'POST'
                route_name: 'api_add_locNidosCol'
                swagger_context:
                    summary: 'Añade información sobre nidos a una colonia'
                    
            postEspecies:
                method: 'POST'
                route_name: 'api_add_especies'
                swagger_context:
                    summary: 'Añade información sobre hay más de ua especie en la misma colonia'
                    
                    
            get:
                method: 'GET'
                normalization_context: 
                    groups: ['colonia']

                denormalization_context: 
                    groups: ['colonia']

            getClose:
                method: 'GET'
                route_name: 'api_get_closeColonias'
                normalization_context: 
                    groups: ['colonia']

                denormalization_context: 
                    groups: ['colonia']
                    
            getFav:
                method: 'GET'
                route_name: 'api_get_favoritosCol'
                
            #getVisits:
                #method: 'GET'
                #route_name: 'api_get_visits'
            newVisit:
                method: 'POST'
                route_name: 'api_new_visitaCol'
            statsAnno:
                method: 'GET'
                route_name: 'api_stats_anno'
                
            statsCcaa:
                method: 'GET'
                route_name: 'api_stats_ccaa'
                
            statsProvincia:
                method: 'GET'
                route_name: 'api_stats_provincia'
                
            statsGeneral:
                method: 'GET'
                route_name: 'api_stats_general'
                
            statsAnnoCol:
                method: 'GET'
                route_name: 'api_stats_annoCol'
                
            statsCcaaCol:
                method: 'GET'
                route_name: 'api_stats_ccaaCol'
                
            statsProvinciaCol:
                method: 'GET'
                route_name: 'api_stats_provinciaCol'
                
            statsMunicipioCol:
                method: 'GET'
                route_name: 'api_stats_municipioCol'
                
            statsTipoEdificioCol:
                method: 'GET'
                route_name: 'api_stats_tipoEdificioCol'
                
            statsTipoPropiedadCol:
                method: 'GET'
                route_name: 'api_stats_tipoPropiedadCol'
            

                
        itemOperations:
            get:
                method: 'GET'             
                normalization_context: 
                    groups: ['colonia']

                denormalization_context: 
                    groups: ['colonia']
            

            delete:
                method: 'DELETE'
                
           # put:
            #    method: 'PUT'
             #   route_name: 'api_put_colonia'
              #  normalization_context: 
               #     groups: ['colonia']

                #denormalization_context: 
                 #   groups: ['colonia']
