resources:
    App\Entity\TipoTerritorio:
        attributes:
            pagination_enabled: false
            
        collectionOperations:
            get:
                method: 'GET'
          
        itemOperations:
            get:
                method: 'GET'
