resources:
    App\Entity\VisitasTerritorio:
        attributes:
            pagination_enabled: false
            normalization_context: 
                groups: ['visitaTerr']
            denormalization_context: 
                groups: ['visitaTerr']
            
        collectionOperations:
            post:
                method: 'POST'


            get:
                method: 'GET'
                normalization_context: 
                    groups: ['visitaTerr']

                denormalization_context: 
                    groups: ['visitaTerr']

                
        itemOperations:
            get:
                method: 'GET'
                
            put:
                method: 'PUT'
                route_name: 'api_put_visitaTerr'
                
            delete:
                method: 'DELETE'
                route_name: 'api_del_visitaTerr'
