resources:
    App\Entity\VisitasColonia:
        attributes:
            pagination_enabled: false
            normalization_context: 
                groups: ['visita']
            denormalization_context: 
                groups: ['visita']
            
        collectionOperations:
            post:
                method: 'POST'
                
            get:
                method: 'GET'

            getByUser:
                method: 'GET'
                route_name: 'api_get_visitasCol'
                normalization_context: 
                    groups: ['visita']

                denormalization_context: 
                    groups: ['visita']

                
        itemOperations:
            get:
                method: 'GET'
                
                
            put:
                method: 'PUT'
                route_name: 'api_put_visitaCol'
                
            delete:
                method: 'DELETE'
                route_name: 'api_del_visitaCol'
