<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine.orm.container_repository_factory' shared service.

include_once $this->targetDirs[3].'/vendor/doctrine/orm/lib/Doctrine/ORM/Repository/RepositoryFactory.php';
include_once $this->targetDirs[3].'/vendor/doctrine/doctrine-bundle/Repository/ContainerRepositoryFactory.php';

return $this->privates['doctrine.orm.container_repository_factory'] = new \Doctrine\Bundle\DoctrineBundle\Repository\ContainerRepositoryFactory(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Repository\\AccessTokenRepository' => ['privates', 'App\\Repository\\AccessTokenRepository', 'getAccessTokenRepositoryService.php', true],
    'App\\Repository\\AuthCodeRepository' => ['privates', 'App\\Repository\\AuthCodeRepository', 'getAuthCodeRepositoryService.php', true],
    'App\\Repository\\CensoColoniaRepository' => ['privates', 'App\\Repository\\CensoColoniaRepository', 'getCensoColoniaRepositoryService.php', true],
    'App\\Repository\\CensoMunicipioRepository' => ['privates', 'App\\Repository\\CensoMunicipioRepository', 'getCensoMunicipioRepositoryService.php', true],
    'App\\Repository\\ClientRepository' => ['privates', 'App\\Repository\\ClientRepository', 'getClientRepositoryService.php', true],
    'App\\Repository\\ColoniaRepository' => ['privates', 'App\\Repository\\ColoniaRepository', 'getColoniaRepositoryService.php', true],
    'App\\Repository\\ComunidadesRepository' => ['privates', 'App\\Repository\\ComunidadesRepository', 'getComunidadesRepositoryService.php', true],
    'App\\Repository\\EmplazamientoRepository' => ['privates', 'App\\Repository\\EmplazamientoRepository', 'getEmplazamientoRepositoryService.php', true],
    'App\\Repository\\FavoritosColRepository' => ['privates', 'App\\Repository\\FavoritosColRepository', 'getFavoritosColRepositoryService.php', true],
    'App\\Repository\\FavoritosTerrRepository' => ['privates', 'App\\Repository\\FavoritosTerrRepository', 'getFavoritosTerrRepositoryService.php', true],
    'App\\Repository\\LocNidosColRepository' => ['privates', 'App\\Repository\\LocNidosColRepository', 'getLocNidosColRepositoryService.php', true],
    'App\\Repository\\LocNidosNoColRepository' => ['privates', 'App\\Repository\\LocNidosNoColRepository', 'getLocNidosNoColRepositoryService.php', true],
    'App\\Repository\\ObservacionesTerritorioRepository' => ['privates', 'App\\Repository\\ObservacionesTerritorioRepository', 'getObservacionesTerritorioRepositoryService.php', true],
    'App\\Repository\\OtrasEspeciesRepository' => ['privates', 'App\\Repository\\OtrasEspeciesRepository', 'getOtrasEspeciesRepositoryService.php', true],
    'App\\Repository\\PoblacionesRepository' => ['privates', 'App\\Repository\\PoblacionesRepository', 'getPoblacionesRepositoryService.php', true],
    'App\\Repository\\ProvinciasRepository' => ['privates', 'App\\Repository\\ProvinciasRepository', 'getProvinciasRepositoryService.php', true],
    'App\\Repository\\RefreshTokenRepository' => ['privates', 'App\\Repository\\RefreshTokenRepository', 'getRefreshTokenRepositoryService.php', true],
    'App\\Repository\\SegUsuRepository' => ['privates', 'App\\Repository\\SegUsuRepository', 'getSegUsuRepositoryService.php', true],
    'App\\Repository\\TempUserRepository' => ['privates', 'App\\Repository\\TempUserRepository', 'getTempUserRepositoryService.php', true],
    'App\\Repository\\TemporadaRepository' => ['privates', 'App\\Repository\\TemporadaRepository', 'getTemporadaRepositoryService.php', true],
    'App\\Repository\\TerritorioRepository' => ['privates', 'App\\Repository\\TerritorioRepository', 'getTerritorioRepositoryService.php', true],
    'App\\Repository\\TipoEdificioRepository' => ['privates', 'App\\Repository\\TipoEdificioRepository', 'getTipoEdificioRepositoryService.php', true],
    'App\\Repository\\TipoPropiedadRepository' => ['privates', 'App\\Repository\\TipoPropiedadRepository', 'getTipoPropiedadRepositoryService.php', true],
    'App\\Repository\\TipoTerritorioRepository' => ['privates', 'App\\Repository\\TipoTerritorioRepository', 'getTipoTerritorioRepositoryService.php', true],
    'App\\Repository\\VisitaColoniaImagesRepository' => ['privates', 'App\\Repository\\VisitaColoniaImagesRepository', 'getVisitaColoniaImagesRepositoryService.php', true],
    'App\\Repository\\VisitaTerritorioImagesRepository' => ['privates', 'App\\Repository\\VisitaTerritorioImagesRepository', 'getVisitaTerritorioImagesRepositoryService.php', true],
    'App\\Repository\\VisitasColoniaRepository' => ['privates', 'App\\Repository\\VisitasColoniaRepository', 'getVisitasColoniaRepositoryService.php', true],
    'App\\Repository\\VisitasTerritorioRepository' => ['privates', 'App\\Repository\\VisitasTerritorioRepository', 'getVisitasTerritorioRepositoryService.php', true],
]));
