# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

api_login_anonymous:
    path: '/api/loginAnonymous'
    methods: ['POST']
    defaults:
        _controller: App\Controller\TempUserController::login
        _api_resource_class: App\Entity\TempUser
        
api_list_col:
    path: '/api/listCol'
    methods: ['GET']
    defaults:
        _controller: App\Controller\SeoApisController::listCol
        
api_list_no_col:
    path: '/api/listNoCol'
    methods: ['GET']
    defaults:
        _controller: App\Controller\SeoApisController::listNoCol

api_list_one_no_col:
    path: '/api/listNoCol/{id}'
    methods: ['GET']
    defaults:
        _controller: App\Controller\SeoApisController::listOneNoCol

api_list_one_col:
    path: '/api/listCol/{id}'
    methods: ['GET']
    defaults:
        _controller: App\Controller\SeoApisController::listOneCol

##########APIS PARA RECUPERAR DATOS GEOFRAFICOS####################

api_ccaa:
    path: '/api/ccaa'
    methods: ['GET']
    defaults:
        _controller: App\Controller\SeoApisController::ccaa

api_provincias:
    path: '/api/provincias/{id}'
    methods: ['GET']
    defaults:
        _controller: App\Controller\SeoApisController::provincias

api_municipios:
    path: '/api/municipios/{id}'
    methods: ['GET']
    defaults:
        _controller: App\Controller\SeoApisController::municipios

##################COLONIA#######################################

api_new_colonia:
    path: '/api/colonias'
    methods: ['POST']
    defaults:
        _controller: App\Controller\ColoniaController::newColonia
        _api_resource_class: App\Entity\Colonia
        _api_collection_operation_name: 'post'
        
api_add_locNidosCol:
    path: '/api/colonias/{id}/loc-nidos'
    methods: ['POST']
    defaults:
        _controller: App\Controller\ColoniaController::completaNidos
        _api_resource_class: App\Entity\Colonia
        _api_collection_operation_name: 'postCol'
        
api_add_especies:
    path: '/api/colonias/{id}/otras-especies'
    methods: ['POST']
    defaults:
        _controller: App\Controller\ColoniaController::completaEspecies
        _api_resource_class: App\Entity\Colonia
        _api_collection_operation_name: 'postEspecies'
        
api_get_closeColonias:
    path: '/api/closeCol'
    methods: ['GET']
    defaults:
        _controller: App\Controller\ColoniaController::getColoniasCercanas
        _api_resource_class: App\Entity\Colonia
        _api_collection_operation_name: 'getClose'
        
api_get_favoritosCol:
    path: '/api/colonias/favoritos/{id}'
    methods: ['GET']
    defaults:
        _controller: App\Controller\ColoniaController::getFavoritos
        _api_resource_class: App\Entity\Colonia
        _api_collection_operation_name: 'getFav'
        
api_get_visits:
    path: '/api/usuario/{id}/visitas'
    methods: ['GET']
    defaults:
        _controller: App\Controller\ColoniaController::getVisits
        _api_resource_class: App\Entity\Colonia
        _api_collection_operation_name: 'getVisits'
        
api_new_visitaCol:
    path: '/api/colonias/{id}/visitas'
    methods: ['POST']
    defaults:
        _controller: App\Controller\ColoniaController::newVisit
        _api_resource_class: App\Entity\Colonia
        _api_collection_operation_name: 'newVisit'
        
api_stats_anno:
    path: '/api/especies/{id}/statsAnno'
    methods: ['GET']
    defaults:
        _controller: App\Controller\ColoniaController::estadisticasAnno
        _api_resource_class: App\Entity\Colonia
        _api_collection_operation_name: 'statsAnno'
        
api_stats_ccaa:
    path: '/api/especies/{id}/statsCcaa'
    methods: ['GET']
    defaults:
        _controller: App\Controller\ColoniaController::estadisticasCcaa
        _api_resource_class: App\Entity\Colonia
        _api_collection_operation_name: 'statsCcca'
        
api_stats_provincia:
    path: '/api/especies/{id}/statsProvincia'
    methods: ['GET']
    defaults:
        _controller: App\Controller\ColoniaController::estadisticasProvincia
        _api_resource_class: App\Entity\Colonia
        _api_collection_operation_name: 'statsProvincia'
        
api_stats_general:
    path: '/api/especies/stats'
    methods: ['GET']
    defaults:
        _controller: App\Controller\ColoniaController::estadisticasGeneral
        _api_resource_class: App\Entity\Colonia
        _api_collection_operation_name: 'statsGeneral'
        
api_stats_annoCol:
    path: '/api/especies/{id}/statsAnnoCol'
    methods: ['GET']
    defaults:
        _controller: App\Controller\ColoniaController::estadisticasAnnoCol
        _api_resource_class: App\Entity\Colonia
        _api_collection_operation_name: 'statsAnnoCol'
        
api_stats_ccaaCol:
    path: '/api/especies/{id}/statsCcaaCol'
    methods: ['GET']
    defaults:
        _controller: App\Controller\ColoniaController::estadisticasCcaaCol
        _api_resource_class: App\Entity\Colonia
        _api_collection_operation_name: 'statsCccaCol'
        
api_stats_provinciaCol:
    path: '/api/especies/{id}/statsProvinciaCol'
    methods: ['GET']
    defaults:
        _controller: App\Controller\ColoniaController::estadisticasProvinciaCol
        _api_resource_class: App\Entity\Colonia
        _api_collection_operation_name: 'statsProvinciaCol'
        
api_stats_tipoEdificioCol:
    path: '/api/especies/{id}/statsTipoEdificioCol'
    methods: ['GET']
    defaults:
        _controller: App\Controller\ColoniaController::estadisticasTipoEdificioCol
        _api_resource_class: App\Entity\Colonia
        _api_collection_operation_name: 'statsTipoEdificioCol'
        
api_stats_municipioCol:
    path: '/api/especies/{id}/statsMunicipioCol'
    methods: ['GET']
    defaults:
        _controller: App\Controller\ColoniaController::estadisticasMunicipioCol
        _api_resource_class: App\Entity\Colonia
        _api_collection_operation_name: 'statsMunicipioCol'
        
api_temporada:
    path: '/api/temporadas'
    methods: ['GET']
    defaults:
        _controller: App\Controller\ColoniaController::getTemporadas
        
api_new_favoritosCol:
    path: '/api/colonias/favoritos'
    methods: ['POST']
    defaults:
        _controller: App\Controller\ColoniaController::newFavorito

##################TERRITORIOS#######################################

api_new_territorio:
    path: '/api/territorios'
    methods: ['POST']
    defaults:
        _controller: App\Controller\TerritorioController::newTerritorio
        _api_resource_class: App\Entity\Territorio
        _api_collection_operation_name: 'post'
        
api_add_locNidosNoCol:
    path: '/api/territorios/{id}/loc-nidos'
    methods: ['POST']
    defaults:
        _controller: App\Controller\TerritorioController::completaNidos
        _api_resource_class: App\Entity\Territorio
        _api_collection_operation_name: 'postNoCol'
        
api_new_favoritosTerr:
    path: '/api/territorios/favoritos'
    methods: ['POST']
    defaults:
        _controller: App\Controller\TerritorioController::newFavorito
        
api_get_favoritosTerr:
    path: '/api/territorios/favoritos/{id}'
    methods: ['GET']
    defaults:
        _controller: App\Controller\TerritorioController::getFavoritos
        _api_resource_class: App\Entity\Territorio
        _api_collection_operation_name: 'getFav'
        
api_new_visitaTerr:
    path: '/api/territorios/{id}/visitas'
    methods: ['POST']
    defaults:
        _controller: App\Controller\TerritorioController::newVisit
        _api_resource_class: App\Entity\Territorio
        _api_collection_operation_name: 'newVisit'
        
api_put_visitaTerr:
    path: '/api/visitas-territorios/{id}'
    methods: ['PUT']
    defaults:
        _controller: App\Controller\TerritorioController::editVisit
        _api_resource_class: App\Entity\VisitasTerritorio
        _api_item_operation_name: 'put'
        
        
api_stats_annoTerr:
    path: '/api/especies/{id}/statsAnnoTerr'
    methods: ['GET']
    defaults:
        _controller: App\Controller\TerritorioController::estadisticasAnno
        _api_resource_class: App\Entity\Territorio
        _api_collection_operation_name: 'statsAnno'
        
api_stats_ccaaTerr:
    path: '/api/especies/{id}/statsCcaaTerr'
    methods: ['GET']
    defaults:
        _controller: App\Controller\TerritorioController::estadisticasCcaa
        _api_resource_class: App\Entity\Territorio
        _api_collection_operation_name: 'statsCcca'
        
api_stats_provinciaTerr:
    path: '/api/especies/{id}/statsProvinciaTerr'
    methods: ['GET']
    defaults:
        _controller: App\Controller\TerritorioController::estadisticasProvincia
        _api_resource_class: App\Entity\Territorio
        _api_collection_operation_name: 'statsProvincia'
        
api_stats_generalTerr:
    path: '/api/especies/statsTerr'
    methods: ['GET']
    defaults:
        _controller: App\Controller\TerritorioController::estadisticasGeneral
        _api_resource_class: App\Entity\Territorio
        _api_collection_operation_name: 'statsGeneral'