# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

api_login_anonymous:
    path: '/api/loginAnonymous'
    methods: ['POST']
    defaults:
        _controller: App\Controller\TempUserController::login
        _api_resource_class: App\Entity\TempUser
        
api_list_col:
    path: '/api/listCol'
    methods: ['GET']
    defaults:
        _controller: App\Controller\SeoApisController::listCol
        
api_list_no_col:
    path: '/api/listNoCol'
    methods: ['GET']
    defaults:
        _controller: App\Controller\SeoApisController::listNoCol

api_list_one_no_col:
    path: '/api/listNoCol/{id}'
    methods: ['GET']
    defaults:
        _controller: App\Controller\SeoApisController::listOneNoCol

api_list_one_col:
    path: '/api/listCol/{id}'
    methods: ['GET']
    defaults:
        _controller: App\Controller\SeoApisController::listOneCol

##########APIS PARA RECUPERAR DATOS GEOFRAFICOS####################

api_ccaa:
    path: '/api/ccaa'
    methods: ['GET']
    defaults:
        _controller: App\Controller\SeoApisController::ccaa

api_provincias:
    path: '/api/provincias/{id}'
    methods: ['GET']
    defaults:
        _controller: App\Controller\SeoApisController::provincias

api_municipios:
    path: '/api/municipios/{id}'
    methods: ['GET']
    defaults:
        _controller: App\Controller\SeoApisController::municipios

##################COLONIA#######################################

api_new_colonia:
    path: '/api/colonias'
    methods: ['POST']
    defaults:
        _controller: App\Controller\ColoniaController::newColonia
        _api_resource_class: App\Entity\Colonia
        _api_collection_operation_name: 'post'
        
api_add_locNidosCol:
    path: '/api/colonias/{id}/loc-nidos'
    methods: ['POST']
    defaults:
        _controller: App\Controller\ColoniaController::completaNidos
        _api_resource_class: App\Entity\Colonia
        _api_collection_operation_name: 'postCol'
        
api_add_especies:
    path: '/api/colonias/{id}/otras-especies'
    methods: ['POST']
    defaults:
        _controller: App\Controller\ColoniaController::completaEspecies
        _api_resource_class: App\Entity\Colonia
        _api_collection_operation_name: 'postEspecies'
        
api_get_closeColonias:
    path: '/api/closeCol'
    methods: ['GET']
    defaults:
        _controller: App\Controller\ColoniaController::getColoniasCercanas
        _api_resource_class: App\Entity\Colonia
        _api_collection_operation_name: 'getClose'
        
api_get_favoritosCol:
    path: '/api/favCol/{id}'
    methods: ['GET']
    defaults:
        _controller: App\Controller\ColoniaController::getFavoritos
        _api_resource_class: App\Entity\Colonia
        _api_collection_operation_name: 'getFav'
        
api_get_visits:
    path: '/api/usuario/{id}/visitas'
    methods: ['GET']
    defaults:
        _controller: App\Controller\ColoniaController::getVisits
        _api_resource_class: App\Entity\Colonia
        _api_collection_operation_name: 'getVisits'
        
api_new_visitaCol:
    path: '/api/colonias/{id}/visitas'
    methods: ['POST']
    defaults:
        _controller: App\Controller\ColoniaController::newVisit
        _api_resource_class: App\Entity\Colonia
        _api_collection_operation_name: 'newVisit'
        
api_stats_anno:
    path: '/api/especies/{id}/statsAnno'
    methods: ['GET']
    defaults:
        _controller: App\Controller\ColoniaController::estadisticasAnno
        _api_resource_class: App\Entity\Colonia
        _api_collection_operation_name: 'statsAnno'
        
api_stats_ccaa:
    path: '/api/especies/{id}/statsCcaa'
    methods: ['GET']
    defaults:
        _controller: App\Controller\ColoniaController::estadisticasCcaa
        _api_resource_class: App\Entity\Colonia
        _api_collection_operation_name: 'statsCcca'
        
api_stats_provincia:
    path: '/api/especies/{id}/statsProvincia'
    methods: ['GET']
    defaults:
        _controller: App\Controller\ColoniaController::estadisticasProvincia
        _api_resource_class: App\Entity\Colonia
        _api_collection_operation_name: 'statsProvincia'
