<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'doctrine.dbal.seo_connection' shared service.

include_once $this->targetDirs[3].'/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Connection.php';
include_once $this->targetDirs[3].'/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php';
include_once $this->targetDirs[3].'/vendor/doctrine/dbal/lib/Doctrine/DBAL/Configuration.php';
include_once $this->targetDirs[3].'/vendor/doctrine/dbal/lib/Doctrine/DBAL/Logging/LoggerChain.php';
include_once $this->targetDirs[3].'/vendor/doctrine/event-manager/lib/Doctrine/Common/EventManager.php';
include_once $this->targetDirs[3].'/vendor/symfony/doctrine-bridge/ContainerAwareEventManager.php';
include_once $this->targetDirs[3].'/vendor/doctrine/doctrine-bundle/ConnectionFactory.php';

$a = new \Doctrine\DBAL\Configuration();

$b = new \Doctrine\DBAL\Logging\LoggerChain();
$b->addLogger(($this->privates['doctrine.dbal.logger'] ?? $this->load('getDoctrine_Dbal_LoggerService.php')));
$b->addLogger(($this->privates['doctrine.dbal.logger.profiling.seo'] ?? ($this->privates['doctrine.dbal.logger.profiling.seo'] = new \Doctrine\DBAL\Logging\DebugStack())));

$a->setSQLLogger($b);
$c = new \Symfony\Bridge\Doctrine\ContainerAwareEventManager(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'doctrine.orm.seo_listeners.attach_entity_listeners' => ['privates', 'doctrine.orm.seo_listeners.attach_entity_listeners', 'getDoctrine_Orm_SeoListeners_AttachEntityListenersService.php', true],
]));
$c->addEventSubscriber(($this->privates['vich_uploader.listener.clean.VisitaColonia'] ?? $this->load('getVichUploader_Listener_Clean_VisitaColoniaService.php')));
$c->addEventSubscriber(($this->privates['vich_uploader.listener.clean.VisitaTerritorio'] ?? $this->load('getVichUploader_Listener_Clean_VisitaTerritorioService.php')));
$c->addEventSubscriber(($this->privates['vich_uploader.listener.remove.VisitaColonia'] ?? $this->load('getVichUploader_Listener_Remove_VisitaColoniaService.php')));
$c->addEventSubscriber(($this->privates['vich_uploader.listener.upload.VisitaColonia'] ?? $this->load('getVichUploader_Listener_Upload_VisitaColoniaService.php')));
$c->addEventSubscriber(($this->privates['vich_uploader.listener.remove.VisitaTerritorio'] ?? $this->load('getVichUploader_Listener_Remove_VisitaTerritorioService.php')));
$c->addEventSubscriber(($this->privates['vich_uploader.listener.upload.VisitaTerritorio'] ?? $this->load('getVichUploader_Listener_Upload_VisitaTerritorioService.php')));
$c->addEventListener([0 => 'loadClassMetadata'], 'doctrine.orm.seo_listeners.attach_entity_listeners');

return $this->services['doctrine.dbal.seo_connection'] = ($this->privates['doctrine.dbal.connection_factory'] ?? ($this->privates['doctrine.dbal.connection_factory'] = new \Doctrine\Bundle\DoctrineBundle\ConnectionFactory([])))->createConnection(['url' => $this->getEnv('DATABASE_SEO_URL'), 'driver' => 'pdo_mysql', 'charset' => 'UTF8', 'host' => 'localhost', 'port' => NULL, 'user' => 'root', 'password' => NULL, 'driverOptions' => [], 'serverVersion' => '5.7', 'defaultTableOptions' => []], $a, $c, []);
