<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNVqX8UO\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNVqX8UO/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNVqX8UO.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNVqX8UO\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerNVqX8UO\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'NVqX8UO',
    'container.build_id' => '90a94f04',
    'container.build_time' => 1567103181,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNVqX8UO');
