<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQO14ut4\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQO14ut4/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQO14ut4.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQO14ut4\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQO14ut4\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'QO14ut4',
    'container.build_id' => 'a62cd200',
    'container.build_time' => 1564513970,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQO14ut4');
