<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTEQXWrp\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTEQXWrp/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTEQXWrp.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTEQXWrp\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTEQXWrp\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TEQXWrp',
    'container.build_id' => 'effc7ee9',
    'container.build_time' => 1560756918,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTEQXWrp');
