<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFjwd5x8\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFjwd5x8/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFjwd5x8.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFjwd5x8\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerFjwd5x8\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Fjwd5x8',
    'container.build_id' => '50d04888',
    'container.build_time' => 1550769113,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerFjwd5x8');
