<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEbm3hhn\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEbm3hhn/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerEbm3hhn.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerEbm3hhn\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerEbm3hhn\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Ebm3hhn',
    'container.build_id' => 'adbf73be',
    'container.build_time' => 1553766000,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerEbm3hhn');
